Added FindLoopStartHareTortoise() to check for loops in chapter Question 2_8
robkeim/cracking-the-coding-interview pull request #3
Opened 2023-11-29 12:48 UTC by epachayan

1. Additional function FindLoopStartHareTortoise() included to check for loops in chapter Question 2_8 
2. Related updates in unit tests.
3. Minor typo fix.

2023-12-02 10:31 UTC, robkeim requested changes
Thank you very much for your contribution @epachayan!

I've got a few small nits for you and then I'll merge.

2023-12-02 10:31 UTC, robkeim commented on CrackingTheCodingInterview/Code/Chapter 2/Question2_8.cs
> +            while (hare != null && hare.Next != null)
```suggestion
            while (hare?.Next != null)
```

2023-12-02 10:31 UTC, robkeim commented on CrackingTheCodingInterview/Code/Chapter 2/Question2_8.cs
> +            if (hare == null || hare.Next == null)
```suggestion
            if (hare?.Next == null)
```

2023-12-02 10:31 UTC, robkeim commented on CrackingTheCodingInterview/Code/Chapter 2/Question2_8.cs
> +        public static Node<T> FindLoopStartHareTortoise<T>(Node<T> head)
Could you please add the following comments before this method (for consistency with the other methods in the solution):
```
// Space: O(1)
// Time: O(N)
```

2023-12-04 04:15 UTC, epachayan commented on CrackingTheCodingInterview/Code/Chapter 2/Question2_8.cs
> +        public static Node<T> FindLoopStartHareTortoise<T>(Node<T> head)
raised another PR for the same. Cheers.

2023-12-05 21:11 UTC, robkeim approved these changes

2023-12-05 21:12 UTC, merged

2023-12-05 21:12 UTC, robkeim commented
Thank you @epachayan!